### ISSUE TITLE
Pair1: For the workload whose performance was measure, conjecture alternative implementation that performance better/worse under the given workload

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#23]
The workload measured in #21, we should "Conjecture that some alternative concrete implementation of the datatype performs better/worse on these workloads. Use a different representation than the other pairs in your group (or get in touch with the course assistant). Motivate and write down your conjecture."

**Comment by mawkler** [comment]
In our new implementation we will change the internal representation of List from Java's ArrayList to LinkedList. Java's ArrayList uses an internal data structure consisting of an array.

## Concatenate many big lists

To concatenate Array Lists one would need to allocate new memory every time the array's previously allocated memory gets used up, and write every element of the list to the larger list. On the contrary, when concatenating a LinkedList less work is needed because one only needs to change the reference of the last pointer in the first list to the address of the head of the second list. In a LinkedList all data can reside where it was originally allocated, and doesn't need to be moved.

Therefore, our theory is that list concatenation using LinkedList will be significantly faster.

## Sort a large list

If the elements in the list to be sorted are very large LinkedList would probably be faster than ArrayList because of the argument made previously, i.e. because reassigning pointers is faster than moving large chunks of data in the memory. However, if the elements are relatively small an ArrayList would probably be faster.

One could guess that most sorting algorithms would have to traverse the list to make comparisons when sorting. Using ArrayList the elements would be stored consecutively in memory favouring the way data is passed from main memory into the cache. When sorting a LinkedList however, the data is scatted all over memory which in this case would make traversing it slower.

Because we in our case are sorting integers (which are smaller than pointers) we believe that the ArrayList will be faster than LinkedList.

## Read randomly from a list

Every time an item is read from the list its address must be located. In the case of an ArrayList, this can be computed in constant time. However, when using a linked list one has to iterate through all preceding items in the list to find the correct address. Therefore we conjecture that the LinkedList is slower than the ArrayList.
