### ISSUE TITLE
Pair2: For the workload whose performance was measure, conjecture alternative implementation that performance better/worse under the given workload

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#24]
The workload measured in #21, we should "Conjecture that some alternative concrete implementation of the datatype performs better/worse on these workloads. Use a different representation than the other pairs in your group (or get in touch with the course assistant). Motivate and write down your conjecture."

**Comment by JonasNorlinder** [comment]
# SumNumbers

_Current implementation: ArrayList, alternative implementation: LinkedList_

Best running time that can be achieved when traversing the list in a single thread is `O(n)`. This is obtained in the original implementation using the builtin Java `ArrayList`, and is still valid in a new implementation using `LinkedList`. Changing `ArrayList` to `LinkedList` won't affect it's algorithmic complexity (given we use an iterator to traverse the list), however, because the nodes in `LinkedList` are most likely not allocated consecutively in memory, we theorize that we will see a performance decrease compared to an `ArrayList` due to worse spatial locality in memory, i.e. in `ArrayList`, the next item is close in memory and thus the processor can prefetch the data into it's cache, while `LinkedList` nodes are far away from each other in memory which makes cache prefetching more difficult and sometimes even impossible.

The memory usage depends on the way that the `ArrayList` pre-allocates memory, but in theory the active memory usage should go up when using a `LinkedList` since the list elements require more memory compared to using an array in the `ArrayList`.

# InsertMany

_Current implementation: ArrayList, alternative implementation: LinkedList_

When inserting elements in the begining of a `ArrayList` the entire array needs to be shifted. Therefore the time complexity of adding _n_ elements into the list is `O(n^2)`. By changing to a `LinkedList` the algorithmic time complexity of adding _n_ elements is `O(n)`, since the addition of a single element takes constant time. Therefore, one could assume, that the `LinkedList` implementation ought to be faster by a factor of _n_. However, just as bad spatial locality ruined performance in case of the `SumNumbers` workloads, the same applies in this case; if we have a cache miss for every insertion we might loose the performance "gained" from having a better time complexity. We believe, however, that `LinkedList` will still be faster, since even though the alternative implementation has worse spatial locality, it has better temporal locality, i.e. since the first node in the list was just inserted the processor keeps it in cache for a while before evicting it, thus we shouldn't suffer as much from any cache misses.

In regards to memory usage, there will be the same consequences as descibed above.

**Comment by JonasNorlinder** [comment]
# RandomRemoves

_Current implementation: ArrayList, alternative implementation: LinkedList_

The worst-case running time for `ArrayList` is achieved when removing the first element, which will be `O(n)` since we have to shift the entire array. The worst-case running time for `LinkedList` is achieved when removing the element in the middle (since it's double linked), we have to traverse the list and update the pointer; the running time is then `O(n)`. Just as in the cases for `InsertMany` and `SumNumbers` workloads, the `LinkedList` implementation will have considerably worse spatial locality which increases the risk of cache misses. Since we are removing at random position both data structures will have the same temporal locality. Different from `SumNumbers` workload, the `RandomRemove` workload with `LinkedList` implementation would not be saved by temporal locality, and thus perform considerably worse than its `ArrayList` implementation.

In regards to memory usage, there will be the same consequences as descibed in `SumNumbers`.
