### ISSUE TITLE
Pair1: Evaluate performance of the new implementation against your conjecture

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#27]
For the conjecture in #23 implemented in #25 , evaluate the performance against your conjecture.

Deliverable: What was the achieved performance? Expected or not? What's happening?

**Comment by mawkler** [comment]
# Performance with LinkedList implementation

Our conjectures regarding sorting and reading randomly from a list were correct. However, we were wrong about list concatenation. Upon further investigation we realized that the implementation of list concatenation in LinkedList does not make use of the underlying data structure the way we thought (see #23). Because of this, each item is added individually to a new list just like in an ArrayList, and therefore list concatenation in LinkedList is slower than in ArrayList.

## Concatenate many big lists

- **Runtime with ArrayList:** 0.050s
- **Runtime with LinkedList:** 0.319s

![Concatenate many big lists](http://user.it.uu.se/~jowe3751/mp/sprint3/measurements/concat.png)

## Sort a large list

- **Runtime with ArrayList:** 0.959s
- **Runtime with LinkedList:** 1.141s

![Sort a large list](http://user.it.uu.se/~jowe3751/mp/sprint3/measurements/sort.png)

## Read randomly from list

- **Runtime with ArrayList:** 0.058s
- **Runtime with LinkedList:** 1.170s

![Read randomly from list](http://user.it.uu.se/~jowe3751/mp/sprint3/measurements/random.png)
