### ISSUE TITLE
Get used to test infrastructure in pair 2, add a test and write documentation 

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#4]
According to instructions we need to
"understand the testing infrastructure and add a test for the function that you intend to add. Write a working note documenting how to add a test, so that the next year’s students could benefit from your understanding."

Deliverable: a test for the function decided upon in #2  and a a markdown file describing how to add a test

**Comment by JonasNorlinder** [comment]
# How to add a test for math module
All tests are found in `voc/tests`. Since math is a part of `stdlib` one should create `test_math.py` within `voc/tests/stdlib`.

All tests should to import two things:
 - `import unittest` (if you want to use e.g. `@unittest.expectedFailure`)
- `from ..utils import TranspileTestCase`

Then create your class to be used for tests which should inherit from TranspileTestCase, in our case `class MathModuleTests(TranslpileTestCase).

To add a test, you add a method to your class, e.g. `def test_sqrt(self)`. Within that method you should call `self.assertCodeExecution(PYTHON_CODE_HERE)`. From the documentation on `assertCodeExecution` is: "Run code as native python, and under Java and check the output is identical".
